spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:file:./pm
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone: Asia/Seoul

logging:
  level:
      kr.tinywind: TRACE
      org.springframework: INFO
      org.hibernate: INFO
      org.h2: INFO

server:
    error:
        whitelabel:
            enabled: true
    port: 80